name: bipou_frontend
description: Aplicativo de credenciamento do evento universitario Bipou.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.11.0
  mobile_scanner: ^7.4.0
  path_provider: ^2.1.6
  qr: ^3.0.2
  qr_flutter: ^4.1.0
  share_plus: ^13.3.0
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - logo-ufs-azul.png
    - MarcaDSI2026.png
